name: Deploy to production
on:
  push:
    branches: [ main ]

jobs:
  install:
    name: Install
    runs-on: ubuntu-20.04
    steps:
      - name: install composer and npm
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: claris-stammtisch.ch
          username: dunko
          key: ${{ secrets.AD13_SECRET }}
          port: 22
          script: |
            cd /var/www/claris-stammtisch/
            git pull origin main
            git status
